server:
  port: 8080

dubbo:
  application:
    id: ilss-consumer
    name: ilss-consumer
  registry:
    protocol: zookeeper
    address: server-a:2181,server-b:2181,server-c:2181
    id: registry-1
  protocol:
    name: dubbo
    port: 20889
  consumer:
    version: 1.0

spring:
  application:
    name: ilss-consumer

